quarkus:
  swagger-ui:
    path: /swagger-ui
    enable: true

  http:
    cors: true
    host: localhost

  # Database
  flyway:
    migrate-at-start: true
  datasource:
    db-kind: postgresql
    username: ${POSTGRES_USER_FW:default_user}
    password: ${POSTGRES_PASSWORD_FW:default_pass}
    jdbc:
      url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_FW:default_db}

  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

"%prod":
  quarkus:
    http:
      host: 0.0.0.0
    datasource:
      username: postgres
      password: 12345678
      jdbc:
        max-size: 90
        driver: org.postgresql.Driver
        url: jdbc:postgresql:///postgres
        additional-jdbc-properties:
          cloudSqlInstance: eval-appart:europe-west2:eval-appart
          socketFactory: com.google.cloud.sql.postgres.SocketFactory